bidding/urls.py
from django.urls import path
from bidding import views

app_name = 'bidding'

urlpatterns = [
    path('home/', views.home, name ='home'),
    path('', views.login_page, name='login'),
    path('register_user/', views.register_user, name='register_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('user_bid/<int:p_id>/', views.user_bid, name='user_bid'),
    path('bid_list/<int:p_id>/', views.bid_list, name='bid_list'),
    path('edit_bid_list/<int:p_id>/<str:location>', views.edit_bid_list, name='edit_bid_list'),
    path('delete_bid_list/<int:p_id>/<str:location>', views.delete_bid_list, name='delete_bid_list'),
    path('user_bid_list/', views.user_bid_list, name='user_bid_list'),
    path('user_pending_orders/', views.user_pending_orders, name='user_pending_orders'),
    path('delivered_orders/', views.delivered_orders, name='delivered_orders'),
    path('ordered_log/', views.ordered_log, name='ordered_log'),
    path('changestatus/<int:pk>', views.changestatus, name='changestatus'),

]

delivery_bidding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bidding.urls'))
]

bidding/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Product(models.Model):
    prod_name = models.CharField(max_length=150)
    prod_id = models.IntegerField()
    description = models.TextField(max_length=264, blank=True)
    weight = models.PositiveIntegerField(default=2)

    def __str__(self):
        return self.prod_name


class biddedAmount(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    days = models.PositiveIntegerField()
    cost = models.FloatField()
    location = models.CharField(max_length=150)

    class Meta:
        unique_together = ('product', 'name', 'location')

    def __str__(self):
        return self.name.username


status_choice = (
    ('Order Received', 'Order Received'),
    ('Order Shipped', 'Order Shipped'),
    ('Out for delivery', 'Out for delivery'),
    ('Delivered', 'Delivered'),
)


class pending_orders(models.Model):
    product = models.CharField(max_length=150)
    order_id = models.CharField(max_length=100)
    address = models.CharField(max_length=150)
    pincode = models.PositiveIntegerField()
    phone_num = models.PositiveIntegerField()
    customer = models.CharField(max_length=150)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    mail = models.EmailField(max_length=150)
    status = models.CharField(max_length=100, choices=status_choice, default='Order Received')

    def __str__(self):
        return self.name.username

bidding/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import biddedAmount


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        labels = {
            'username': 'Username',
            'email': 'E-mail',
            'first_name': 'First Name',
            'last_name': 'Last Name'
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Username is already taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is already registered")
        return email

    def clean_password1(self):
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('confirm_password')
        if password != password1:
            raise forms.ValidationError("Passwords do not match!")
        return password1


class BiddingForm(forms.ModelForm):
    class Meta:
        model = biddedAmount
        fields = ['days', 'cost', 'location']
        labels = {
            'cost': 'Cost(in rupees):',
            'days': 'Estimated Number of Days :',
            'location': 'Delivery Location :'
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = biddedAmount
        fields = ['days', 'cost']
        labels = {
            'cost': 'Cost(in rupees):',
            'days': 'Estimated Number of Days :',
        }

bidding/views.py
import json

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
import requests
from django.template.loader import render_to_string
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from bidding.models import Product, biddedAmount, pending_orders
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from .forms import RegisterForm, BiddingForm, EditForm

product_api_key = 'GQIJ8cdB0aqCVM7y449lNgsquxP2w6'

bidding_api_key = 'bDjAHFychTio4BKHnd3DWEB9jKAUJl'


@login_required
def home(request):
    url = 'http://127.0.0.1:8000/shopping/product_list/?api_key=' + product_api_key
    response = requests.get(url)
    products = response.json()
    print('in home')
    for product in products:
        if not Product.objects.filter(prod_name=product['prod_name'],
                                      prod_id=product['pk']).exists():
            print('added new product')

            p = Product.objects.create(prod_name=product['prod_name'],
                                       prod_id=product['pk'],
                                       description=product['description'],
                                       weight=product['weight'])
            p.save()
        else:
            p = Product.objects.filter(prod_name=product['prod_name'], prod_id=product['pk'])
            p[0].description = product['description'],
            p[0].weight = product['weight']
            p[0].save()
    prod_list = Product.objects.all()
    return render(request, 'bidding/homepage.html', {'prod_list': prod_list})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.GET:
                return redirect(request.GET['next'])
            return redirect('bidding:home')

    return render(request, 'bidding/login.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    return redirect('bidding:home')


def register_user(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('bidding:login')

    return render(request, 'bidding/register.html', {'form': form})


@login_required
def bid_list(request, p_id):
    if p_id:
        form = BiddingForm()
        bidded_list = biddedAmount.objects.filter(product__prod_id=p_id)
        return render(request, 'bidding/bid_list.html', {'bidded_list': bidded_list, 'pk': p_id, 'form': form})


def user_bid_list(request):
    bidded_list = biddedAmount.objects.filter(name=request.user)
    return render(request, 'bidding/user_bid_list.html', {'bidded_list': bidded_list})


def delete_bid_list(request, p_id, location):
    if p_id and location:
        try:
            product = Product.objects.get(pk=p_id)
            instance = biddedAmount.objects.get(product=product, name=request.user, location=location.lower())
            url = 'http://127.0.0.1:8000/shopping/delivery_bid/?api_key=' + bidding_api_key

            data = json.dumps(
                {'name': request.user.username, 'name_id': request.user.pk, 'product': product.prod_id,
                 'location': location.lower(),
                 'msg': 'delete', 'days': instance.days, 'cost': instance.cost, })
            print('sending to sportshub')

            requests.post(url=url, data=data)
            instance.delete()
        except:
            pass
        return redirect('bidding:user_bid_list')


def edit_bid_list(request, p_id, location):
    if p_id and location:
        product = Product.objects.get(pk=p_id)
        instance = biddedAmount.objects.get(product=product, name=request.user, location=location.lower())
        form = EditForm(instance=instance)
        if request.method == 'POST':
            form = EditForm(request.POST)
            if form.is_valid():
                product = Product.objects.get(pk=p_id)
                name = request.user
                days = form.cleaned_data['days']
                cost = form.cleaned_data['cost']
                instance = biddedAmount.objects.get(product=product, name=request.user, location=location.lower())
                instance.days = days
                instance.cost = cost
                instance.save()
                url = 'http://127.0.0.1:8000/shopping/delivery_bid/?api_key=' + bidding_api_key

                data = json.dumps(
                    {'name': request.user.username, 'name_id': request.user.pk, 'product': product.prod_id,
                     'days': days, 'cost': cost, 'location': location.lower()})
                requests.post(url=url, data=data)
                return redirect('bidding:user_bid_list')

        return render(request, 'bidding/user_bid.html', {'form': form})


@login_required
def user_bid(request, p_id):
    if p_id:
        form = BiddingForm()
        if request.method == 'POST':
            form = BiddingForm(request.POST)
            if form.is_valid():
                product = Product.objects.get(prod_id=p_id)
                name = request.user
                days = form.cleaned_data['days']
                cost = form.cleaned_data['cost']
                location = form.cleaned_data['location']
                if biddedAmount.objects.filter(product=product, name=request.user, location=location.lower()).exists():
                    instance = biddedAmount.objects.get(product=product, name=request.user, location=location.lower())
                    instance.days = days
                    instance.cost = cost
                    instance.save()
                else:
                    biddedAmount.objects.create(name=name, product=product, days=days,
                                                cost=cost, location=location.lower())

                url = 'http://127.0.0.1:8000/shopping/delivery_bid/?api_key=' + bidding_api_key

                data = json.dumps({'name': request.user.username, 'name_id': request.user.pk, 'product': p_id,
                                   'days': days, 'cost': cost, 'location': location.lower()})
                requests.post(url=url, data=data)
                return redirect('bidding:bid_list', p_id)
        return render(request, 'bidding/user_bid.html', {'form': form})


@api_view(['POST'])
def ordered_log(request):
    if request.method == 'POST':
        data = JSONParser().parse(request)
        # t = Tournaments.objects.get(name=data['tournament'])
        # data['tournament'] = t.pk

        # tournament = get_object_or_404(Tournaments, title=request.data.get('tournament'))
        product = data['product']
        name = data['name']
        pincode = data['pincode']
        product_name = data['prod_name']
        address = data['address']
        phonenum = data['phonenum']
        customer_name = data['customer_name']
        mail = data['mail']
        location = data['location']
        order_id = data['order_id']
        print('prod_id', product)
        print('name_id', name)
        print('pincode', pincode)
        print('in ordered log')
        try:

            user = biddedAmount.objects.get(product__prod_id=product, name_id=name, location=location.lower())
            print('got user')
            pending_orders.objects.create(product=product_name, address=address, pincode=pincode, phone_num=phonenum,
                                          customer=customer_name, name=user.name, mail=mail, order_id=order_id)
            print('created pending order')
            return Response({'created'}, status=status.HTTP_201_CREATED)
        except:
            print('bad request')
            return Response({'Bad request'}, status=status.HTTP_400_BAD_REQUEST)


@login_required
def user_pending_orders(request):
    pendingorders = pending_orders.objects.filter(name=request.user).exclude(status='Delivered')
    return render(request, 'bidding/user_pending_orders.html', {'orders': pendingorders})


@login_required
def delivered_orders(request):
    pendingorders = pending_orders.objects.filter(name=request.user, status='Delivered')
    return render(request, 'bidding/delivered_orders.html', {'orders': pendingorders})


@login_required
def changestatus(request, pk):
    if pk:
        pending_order = pending_orders.objects.get(pk=pk)
        new_status = ''
        if pending_order.status == 'Order Received':
            pending_order.status = 'Order Shipped'
            new_status = 'Order Shipped'
        elif pending_order.status == 'Order Shipped':
            pending_order.status = 'Out for delivery'
            new_status = 'Out for delivery'
        elif pending_order.status == 'Out for delivery':
            pending_order.status = 'Delivered'
            new_status = 'Delivered'

        if new_status != '':
            subject = 'Your order status: ' + new_status
            body = '''Dear User,
                                You order with Order Id ''' + pending_order.order_id + ''' is changed its status to ''' + new_status + ''' You will receive your order soon.  
                                Thank You for ordering'''
            try:
                send_mail(subject, body, settings.EMAIL_HOST_USER, [pending_order.mail], fail_silently=True)

            except:
                pass
        pending_order.save()
        return redirect('bidding:user_pending_orders')

bidding/templates/bidding/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Delivery Bidding</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Quicksand:400,700%7CCabin:400%7CDancing+Script" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}"/>

		<!-- Owl Carousel -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
		<link type="text/css" rel="stylesheet" href="{% static 'css/owl.theme.default.css'%}" />

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

		<!-- Custom stylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

        <style>
        </style>

    </head>

	<body>

		<!-- Header -->
		<header id="header">
			<!-- Bottom nav -->
			<div id="bottom-nav">
				<div class="container">
				<nav id="nav">

					<!-- nav -->
					<ul class="main-nav nav navbar-nav">
                        <li class="white-text" style="color: black;font-weight: 700"><a href="{% url 'bidding:home' %}"><i>Delivery Squad</i></a></li>
						<li><a href="{% url 'bidding:home' %}">Home</a></li>
						{% if request.user.is_authenticated %}
    						<li><a href="{% url 'bidding:user_bid_list' %}">Your Bids</a></li>
                            <li><a href="{% url 'bidding:user_pending_orders' %}">Your pending orders</a></li>
                            <li><a href="{% url 'bidding:delivered_orders' %}">Delivered orders</a></li>
                        {% endif %}
					</ul>
					<!-- /nav -->

					<!-- contact nav -->
					<ul class="contact-nav nav navbar-nav">
						{% if request.user.is_authenticated %}
                            <li><a href="{% url 'bidding:logout_user' %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url 'bidding:login' %}">Log In</a></li>
                            <li><a href="{% url 'bidding:register_user' %}">Register</a></li>
                        {% endif %}
					</ul>
					<!-- contact nav -->

				</nav>
				</div>
			</div>
			<!-- /Bottom nav -->


		</header>
		<!-- /Header -->



        {% block content %}

        {% endblock %}



        <!-- Footer -->
        <footer id="footer">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- copyright -->
					<div class="col-md-4">

						<span class="copyright">Delivery Bidding</span>

					</div>
					<!-- /copyright -->

					<!-- footer nav -->
					<div class="col-md-8">
						<nav class="footer-nav">
							<a href="#">Home</a>
							<a href="#">Your Bids</a>
							{% if request.user.is_authenticated %}
                                <a href="{% url 'bidding:logout_user' %}">Log Out</a>
                            {% else %}
                                <a href="{% url 'bidding:login' %}">Log In</a>
                                <a href="{% url 'bidding:register_user' %}">Register</a>
                        {% endif %}
						</nav>
					</div>
					<!-- /footer nav -->

				</div>
				<!-- /row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- Preloader -->
		<div id="preloader">
			<div class="preloader">
				<span></span>
				<span></span>
				<span></span>
			</div>
		</div>
		<!-- /Preloader -->

		<!-- jQuery Plugins -->
		<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
		<script type="text/javascript" src="{% static 'js/google-map.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

	</body>
</html>

bidding/templates/bidding/bid_list.html
{% extends "bidding/base.html" %}
{% load static %}

{% block content %}

    <!-- Reservation -->
		<div id="reservation" class="section">

            <!-- Backgound Image -->
			<div class="bg-image" style="background-image:url({% static 'img/bid.jpg' %})"></div>
			<!-- /Backgound Image -->

			<!-- container -->
			<div class="container" style="padding: 100px 0">

				<!-- row -->
				<div class="row">
					<!-- opening time -->
					<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
						<div class="opening-time row"  style="min-height:400px">
							<div class="section-header text-center">
								<h3 class="title white-text">Bidding List</h3>
							</div>
                            <div class="col-md-12 text-center" style="padding-bottom: 20px">
                                <a href="{% url 'bidding:user_bid' pk %}"><button class="button">Make a new bid</button></a>
							</div>

							<ul>
                                {% if bidded_list %}
                                    {% for bidded in bidded_list %}
                                        <li>
                                            <h4 class="day">{{ bidded.name }}</h4>
                                            <h4 class="hours">Rs. {{ bidded.cost }}, Within {{ bidded.days }} days to
                                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                    width="12" height="12"
                                                    viewBox="0 0 172 172"
                                                    style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#e67e22"><path d="M86,18.8125c-28.62187,0 -52.13803,23.24635 -52.2724,51.86822c0.13437,10.75 3.36095,21.23178 9.67657,30.10053c0.13438,0.26875 0.26665,0.53697 0.5354,0.80572l36.81927,48.91303l0.13385,0.13385c1.34375,1.6125 3.22605,2.4198 5.1073,2.4198c1.88125,0 3.76355,-0.94167 5.1073,-2.4198l0.13385,-0.13385l36.6828,-48.91303c0.40312,-0.40312 0.67345,-0.6724 0.9422,-1.2099c6.04687,-8.73437 9.2724,-19.08073 9.2724,-29.69635c0,-28.4875 -23.3823,-51.86822 -52.13855,-51.86822zM86,26.875c24.32187,0 44.07605,19.75208 44.07605,43.93958c0,9.00312 -2.68802,17.6047 -7.92865,25.1297c-0.13437,0.13437 -0.27032,0.26718 -0.27032,0.40155l-35.87708,47.8396l-35.74322,-47.70312l-0.13385,-0.13647c0,-0.13437 -0.13595,-0.13333 -0.27032,-0.2677c-5.24062,-7.525 -8.0625,-16.26042 -8.0625,-25.26355c0.13437,-24.32188 20.0224,-43.93958 44.2099,-43.93958zM86,44.4776c-13.975,0 -25.3974,11.0198 -25.3974,24.59168c0,13.57188 11.4224,24.72552 25.3974,24.72552c13.975,0 25.3974,-11.0198 25.3974,-24.59167c0,-13.57187 -11.4224,-24.72553 -25.3974,-24.72553zM86,52.5401c9.54062,0 17.3349,7.39168 17.3349,16.52918c0,9.1375 -7.79428,16.66302 -17.3349,16.66302c-9.54063,0 -17.3349,-7.39167 -17.3349,-16.52917c0,-9.1375 7.79428,-16.66303 17.3349,-16.66303z"></path></g></g></svg>
                                                {{ bidded.location }}.</h4>
                                        </li>
                                    {% endfor %}
                                {% endif %}
							</ul>
						</div>
					</div>
					<!-- /opening time -->

				</div>
				<!-- /row -->

			</div>
			<!-- /container -->

		</div>
		<!-- /Reservation -->

{% endblock %}

bidding/templates/bidding/delivered_orders.html
{% extends "bidding/base.html" %}
{% load static %}

{% block content %}

     <div class="banner-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style="background-image:url({% static 'img/blog-img.jpg' %})"></div>
        <!-- /Backgound Image -->

        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2 class="white-text title">Orders Delivered</h2>
                </div>
            </div>
        </div>
    </div>

    <div id="events" class="section">
        <div class="container">
            <div class="row">
                <!-- section header -->
                <div class="section-header text-center">
                    <h2 class="title">Orders Delivered</h2>
                </div>
                <!-- /section header -->
                {% if orders %}
                    {% for order in orders %}
                        <div class="col-md-4">
                            <div class="event">
                                <div class="event-content">
                                    <h3>{{ order.customer }}</h3>
                                    <h3>{{ order.product }}</h3>
                                    <h5>Address : {{ order.address }} , {{ order.pincode }}</h5>
                                    <h5>Phone Number : {{ order.phone_num }}</h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="home-wrapper">
                        <div class="col-md-10 col-md-offset-1 text-center">
                            <div class="home-content" style="padding-bottom: 107px">
                                <h4 class="lead">There are no delivered orders.</h4>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

bidding/templates/bidding/login.html
{% extends "bidding/base.html" %}
{% load static %}

{% block content %}

    <div class="banner-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style="background-image:url({% static 'img/blog-img.jpg' %})"></div>
        <!-- /Backgound Image -->

        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2 class="white-text title">Log In</h2>
                </div>
            </div>
        </div>
    </div>


    <div id="blog" class="section" style="padding-bottom: 150px">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="blog-reply-form">
                          <h3 class="title" style="color:black">Log In</h3>
                          <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}<br>
                            <center><input type="submit" class="button" value="Log In"></center>
                          </form>
                        </div>
                    </div>
				</div>
			</div>
		</div>

{% endblock %}

bidding/templates/bidding/user_bid_list.html
{% extends "bidding/base.html" %}
{% load static %}

{% block content %}

    <div class="banner-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style="background-image:url({% static 'img/blog-img.jpg' %});"></div>
        <!-- /Backgound Image -->

        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center"><br>
                    <h2 class="white-text title">Product Biddings</h2>
                </div>
            </div>
        </div>
    </div>

    <div id="events" class="section">
            <div class="container">
                <div class="row">
					<!-- section header -->
					<div class="section-header text-center">
						<h4 class="sub-title"></h4>
						<h2 class="title">Your Biddings</h2>
					</div>
					<!-- /section header -->
                    {% if bidded_list %}
                        {% for bidded in bidded_list %}
                            <div class="col-md-4">
                                <div class="event">
                                    <div class="event-content">
                                        <h4>{{ bidded.name }}</h4>
                                        <h4>{{ bidded.product }}</h4>
                                        <p>Delivery Charges : {{ bidded.cost }}</p>
                                        <p>Estimated delivery by {{ bidded.days }} working days to location {{ bidded.location }}.</p>
                                        <a href="{% url 'bidding:edit_bid_list' bidded.product_id    bidded.location %}"><button class="button">Edit</button></a>
                                        <a href="{% url 'bidding:delete_bid_list' bidded.product_id    bidded.location %}"><button class="button">Delete</button></a><br>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="home-wrapper">
                            <div class="col-md-10 col-md-offset-1 text-center">
                                <div class="home-content" style="padding-bottom: 33px">
                                    <h4 class="lead">Oops..! Looks like you haven't bid on any products yet. Click here to start bidding on products according to your available services. </h4>
                                    <a href="{% url 'bidding:home' %}"><button class="main-button">Start Bidding -></button></a>
                                </div>
                            </div>

            			</div>
                    {% endif %}
				</div>
			</div>
		</div>

{% endblock %}

bidding/templates/bidding/user_pending_orders.html
{% extends "bidding/base.html" %}
{% load static %}

{% block content %}

     <div class="banner-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style="background-image:url({% static 'img/blog-img.jpg' %})"></div>
        <!-- /Backgound Image -->

        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2 class="white-text title">Pending Orders</h2>
                </div>
            </div>
        </div>
    </div>

    <div id="events" class="section">
        <div class="container">
            <div class="row">
                <!-- section header -->
                <div class="section-header text-center">
                    <h4 class="sub-title">Orders to be delivered</h4>
                    <h2 class="title">Pending Orders</h2>
                </div>
                <!-- /section header -->
                {% if orders %}
                    {% for order in orders %}
                        <div class="col-md-4">
                            <div class="event">
                                <div class="event-content">
                                    <h3>{{ order.customer }}</h3>
                                    <h3>{{ order.product }}</h3>
                                    <h5>Address : {{ order.address }} , {{ order.pincode }}</h5>
                                    <h5>Phone Number : {{ order.phone_num }}</h5>
                                    <h5>Status: {{ order.status }}</h5>
                                    <a href="{% url 'bidding:changestatus' order.pk %}"><button class="button">Change Status</button></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="home-wrapper">
                        <div class="col-md-10 col-md-offset-1 text-center">
                            <div class="home-content" style="padding-bottom: 107px">
                                <h4 class="lead">Oops..! Looks like you have no new orders to be delivered.</h4>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}